framework:
  rate_limiter:
    anonymous_api:
      policy: 'fixed_window'
      limit: 20
      interval: '5 minutes'
    authenticated_api:
      policy: 'token_bucket'
      limit: 5000
      rate: { interval: '15 minutes', amount: 500 }