# Stage 1: Install PHP dependencies
FROM composer:2 AS vendor
WORKDIR /app
COPY composer.json ./
COPY composer.loc[k] ./
RUN composer install --no-dev --optimize-autoloader --ignore-platform-reqs

# Stage 2: Final image
FROM php:8.5-apache

RUN pecl install redis || true
RUN docker-php-ext-enable redis

RUN docker-php-ext-install pdo pdo_mysql pcntl intl

COPY php.ini /usr/local/etc/php/conf.d/custom.ini

RUN a2enmod rewrite
RUN a2enmod ssl

RUN echo "PassEnv DOMAIN" >> /etc/apache2/apache2.conf
COPY 000-default.conf /etc/apache2/sites-available/

RUN mkdir -p /etc/ssl/certs
COPY ssl-certs/* /etc/ssl/certs/
COPY ssl-certs /ssl-certs

RUN a2ensite 000-default

WORKDIR /var/www/html

COPY --from=vendor /app/vendor ./vendor
COPY . .
RUN echo "APP_ENV=prod\nAPP_DEBUG=0" > .env

EXPOSE 80 443
