FROM php:8.2-apache

RUN docker-php-ext-install pdo pdo_mysql

RUN a2enmod rewrite
RUN a2enmod ssl

RUN echo "PassEnv DOMAIN" >> /etc/apache2/apache2.conf
COPY 000-default.conf /etc/apache2/sites-available/

RUN mkdir -p /etc/ssl/certs
COPY ssl-certs/* /etc/ssl/certs

#RUN a2ensite 000-default

EXPOSE 80 443

WORKDIR /var/www/html