apiVersion: v1
kind: ConfigMap
metadata:
  name: lingwhaat-config
  namespace: lingwhaat
data:
  APP_ENV: "prod"
  APP_DEBUG: "0"
  DOMAIN: "lingwhaat.com"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "lingwhaat"
  RATE_LIMITER_WHITELISTED_IP: "127.0.0.1"
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_PORT: "9200"
  LOCK_DSN: "redis://redis:6379"
  MESSENGER_TRANSPORT_DSN: "doctrine://messenger?table_name=messenger_messages&queue_name=async"
  MESSENGER_WIKIPEDIA_TRANSPORT_DSN: "doctrine://messenger?table_name=messenger_messages&queue_name=wikipedia_async"
  MESSENGER_WIKTIONARY_TRANSPORT_DSN: "doctrine://messenger?table_name=messenger_messages&queue_name=wiktionary_async"
  MESSENGER_WIKIPEDIA_PATTERN_INDEX_TRANSPORT_DSN: "doctrine://messenger?table_name=messenger_messages&queue_name=wikipedia_pattern_index_async"
  MESSENGER_SELECTION_TRANSPORT_DSN: "doctrine://messenger?table_name=messenger_messages&queue_name=selection"
  MESSENGER_MANUSCRIPT_LANGUAGE_SCORE_TRANSPORT_DSN: "doctrine://messenger?table_name=messenger_messages&queue_name=manuscript_language_score_async"
  MESSENGER_WORDS_POPULARITY_TRANSPORT_DSN: "doctrine://messenger?table_name=messenger_messages&queue_name=words_popularity_async"
  MESSENGER_FAILED_DSN: "doctrine://messenger?table_name=messenger_messages&queue_name=failed"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: lingwhaat
data:
  my.cnf: |
    [mysqld]
    general_log = on
    general_log_file = /tmp/mysql.log
