BATCH_SIZE = 32
INPUT_DIM = None
OUTPUT_DIM = None
ENC_EMB_DIM = 256  # Increased from 64
DEC_EMB_DIM = 256  # Increased from 64
HID_DIM = 512      # Increased from 128
ENC_LAYERS = 2     # Multi-layer encoder
DEC_LAYERS = 2     # Multi-layer decoder
ENC_DROPOUT = 0.3  # Regularization
DEC_DROPOUT = 0.3  # Regularization
N_EPOCHS = 100     # More epochs with early stopping
CLIP = 1
LEARNING_RATE = 0.001
PATIENCE = 10      # Early stopping patience
VALIDATION_SPLIT = 0.1  # 10% for validation