BATCH_SIZE = 32
INPUT_DIM = None
OUTPUT_DIM = None
ENC_EMB_DIM = 256  # Increased from 64
DEC_EMB_DIM = 256  # Increased from 64
HID_DIM = 512      # Increased from 128
ENC_LAYERS = 2     # Multi-layer encoder
DEC_LAYERS = 2     # Multi-layer decoder
ENC_DROPOUT = 0.3  # Regularization
DEC_DROPOUT = 0.3  # Regularization
N_EPOCHS = 500     # Increased for large datasets (was 100)
CLIP = 1
LEARNING_RATE = 0.001
PATIENCE = 30      # Increased early stopping patience (was 10)
VALIDATION_SPLIT = 0.05  # 5% for validation (early stopping / model selection)
TEST_SPLIT = 0.05        # 5% held out for honest accuracy evaluation (never trained on)
LR_SCHEDULER_PATIENCE = 10  # Patience for learning rate reduction
MIN_EPOCHS = 20    # Minimum epochs before early stopping can trigger
WEIGHT_DECAY = 1e-5      # L2 regularization to curb overfitting
LABEL_SMOOTHING = 0.1    # Softens targets; improves generalization on noisy IPA