nelmio_api_doc:
  resource: "@NelmioApiDocBundle/config/routing/swaggerui.xml"
  type: rest

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
